name: Deploy Site

on:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build site
        run: bundle exec jekyll build --destination docs --config _config.yml,_config_prod.yml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          commit_message: Deploy site from ${{ github.sha }}
          build_script: |
            cp -r ./blogs/. ./docs/
            cd ./docs
            jekyll build --config _config.yml,_config_prod.yml
        env:
          JEKYLL_ENV: production
